### ISSUE TITLE
send mail is sending to wrong user.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#273] opened 2014-02-04 10:15 UTC
Step to reproduce
1) start 2 client.
2) enable mining 
3) add identitties in each client.
4) add those identities to each other client.
5) Now close the clients.
6) start the 2 clients again
7) compose a mail from one client to other.

 It sends mail to oneself rather than other client.

Tested on Ubuntu and is always reproducible.

**Comment by yuvarajgogoi** [comment] 2014-02-06 06:54
Also only 1 suggestion is given on auto completion in to_field

**Comment by vogel76** [comment] 2014-02-27 15:07
Bug was caused by mess in ContactListEdit, AddressBookModel & QCompleter handling. Lately list of completions (displayed in QCompleter) was merged into single one to avoid redundant entries for the same contact, but other code ie inside ContactListEdit::insertCompletion(const QModelIndex&) was not updated accordingly and caused to select internally different contact):
int row = completionIndex.data(Qt::UserRole).toInt();
  row = row  2; <---- BUGGY REGION
  /DLNFIX consider telling ContactListEdit about addressbookmodel some other way eventually
  QModelIndex index = getKeyhoteeWindow()->getAddressBookModel()->index(row,0);
  auto contact = getKeyhoteeWindow()->getAddressBookModel()->getContact(index);
Right now it works since ContactListEdit has been mostly reimplemented according to address  completion support.

**Closed as completed by vogel76** 2014-02-27 15:07 UTC
Labels: bug, vogel
