### ISSUE TITLE
Display unread messages in the mailbox tree.

### ISSUE THREAD

**Issue by PaulEU** [InvictusInnovations/keyhotee#336] opened 2014-03-31 18:43 UTC
If some mail box contains unread messages should be displayed in bold.  Display the number of unread messages in parentheses.

**Comment by dnotestein** [comment] 2014-03-31 19:55
Is this a duplicate of https://github.com/InvictusInnovations/keyhotee/issues/334 ?

**Closed as completed** 2014-03-31 20:44 UTC
Labels: enhancement, question, unassigned

**Comment by PaulEU** [comment] 2014-03-31 20:49
Yes, it's duplicated. I closed.
