### ISSUE TITLE
New user registering a name that is already reserved...

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#99] opened 2013-12-19 17:15 UTC
When there is a conflict the Keyhotee Founder BADGE next to their ID should changed to a RED CONFLICT badge.

**Comment by dnotestein** [comment] 2013-12-21 22:33
KeyhoteeIds can be requested by a user as an identity before they're synced up with the blockchain, so this means we can't always tell the user right away that ID is not available. Further, even if they are connected up to the blockchain, the name can be registered at any time.  We can show them several possible values for a keyhoteeId they are requesting as an identity:
When not synced, we should probably just display "keyhoteeID ledger not accessible yet". 
When synced, we can display these states: "Registered" (means it is in the blockchain ledge and user owns it), "Unregistered" (means it's available to be registered at the moment, assuming user can mine it before someone else gets it), "Not Available" (can't be registered because it or similar name is already registered to someone else (or there's some other reason this ID cannot be registered, no known case for that now, just closing all the holes) ).

We need code that always checks to see if identity holds the keys for the keyhoteeId it believes it has registered (this check needs to be performed whenever we display info about the identity I think). It's possible that a keyhoteeId could be lost by the user (not the keys, just the registration in the blockchain ledger) in the case of a chain fork and the user should be signaled to this condition.

We need modify to the existing contact info dialog to support additional fields that are useful for identities: setting mining level for identity and an option to show private keys associated with an identity. The mining level display is probably the only controversial issue here. The internal representation is a floating point number from 0 (no mining effort) to 1 (max mining effort) and will be displayed with a sliding bar from 0 to 100%. Presumably, max mining level means all cores utilized at near 100% (e.g. on a four core machine, use four threads). Currently I think we only have control down to the number of threads utilized for the mining. So for initial release, maybe we ought to allow a percentage entry for 0 to 100, and then calculate how many threads to use based on that as a percentage of the number of cores in the machine. However, I also don't think mining with multiple threads has been tested well, so depending on when we release a version with mining enabled, we may just want to always set it to 0 or 1 thread used.

**Comment by dnotestein** [comment] 2013-12-21 22:46
Actually, maybe this leads to a big problem if we don't support multiple identities now. Once an identity is created, we can't change the keyhoteeId I believe, since keys are created based on it. So maybe we need to support multiple identities in the alpha release so that user can create another identity that he can validly register in the blockchain. 

Other option, of course, would be to just not allow specifying keyhoteeId until synched to blockchain for now.

It would be really nice if we can offer some way to register the private keys to a new keyhoteeId also, at some point in the future, if it's feasible. 

Need to discuss multiple identity issue with Bytemaster soon...Bytemaster, please review, then let's discuss and I'll reassign the task as appropriate.

**Comment by dnotestein** [comment] 2013-12-22 05:13
ok, confirmed with Bytemaster that we will need to support ability to create additional identities in a profile in the alpha release. He's going to handle the backend work for this, and we'll modify the contact info page as needed to support identity info discussed above.

**Comment by dnotestein** [comment] 2013-12-28 06:58
The GUI described in the first comment needs to be assigned to someone to implement soon. The most important part is to get the GUI to report the full set of registration states for the keyhoteeID as described in the comment.

**Comment by grzegorzs** [comment] 2013-12-30 21:58
Added status of Keyhotee ID and mining effort
required functions: getKeyhoteeStatus(), getMiningEffort(), setMiningEffort()
b7d85be63003f38d947517e5efc0db83a26fee8a

**Closed as completed by grzegorzs** 2013-12-30 21:58 UTC
Labels: critical, GrzegorzS
