### ISSUE TITLE
backend database loading hangs 

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#36] opened 2013-12-10 22:20 UTC
bts::bitname::detail::name_channel_impl::fetch_loop hangs while loading the database. It is possible that database is corrupted since application was killed earlier after it hungs while mining process.
Inside fetch_next_from_fork_db member fn, catch block is executed each time this function is called:
                     catch ( const fc::exception& e )
                     {
                         elog( "error applying block from this fork, this fork must be invalid\n${e}", ( "e", e.to_detail_string() ) );
                         _fork_db.set_valid( next_block->id(), false );
                     }

In issue attachement is stored zipped Invictus profile directory containing probably broken database.

WARNING: attached file really is a .zip, just renamed to avoid github limitations.
![invictus innovations inc_load_hang zip](https://f.cloud.github.com/assets/6086581/1719281/78886b90-61e9-11e3-92c9-31bcabbd3c83.jpg)

**Comment by bytemaster** [comment] 2013-12-17 00:55
This may be because we changed the format for name transactions... keep an eye out for cases where this is reproduced.

**Comment by dnotestein** [comment] 2013-12-18 20:33
I don't think this has been reproduced since, so I suspect this was caused by the database format change that bytemaster mentioned, so I'm going to close this issue.

**Closed as completed by dnotestein** 2013-12-18 20:33 UTC
Labels: bug, critical, backend-related
